apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template: 
    metadata:
      labels:
        app:
          website
    spec:
      containers:
        - name: website-deployment
          image: image1
          imagePullPolicy: Never
          ports: 
            - containerPort: 80
